import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { supabaseAdmin } from '@/lib/supabase/server';
import { Database } from '@/lib/supabase/types';
import { SupabaseClient } from '@supabase/supabase-js';

const supabase = supabaseAdmin as SupabaseClient<Database>;

/**
 * GET /api/jobs/[id]
 * Get status of a specific job
 * 
 * Returns:
 * {
 *   id: string;
 *   status: 'queued' | 'processing' | 'completed' | 'failed';
 *   created_at: string;
 *   result_url?: string;
 *   error?: string;
 * }
 */
export async function GET(
    req: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { userId } = await auth();

        if (!userId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { id } = await params;

        // Fetch job details
        const { data, error } = await supabase
            .from('jobs')
            .select('*')
            .eq('id', id)
            .eq('user_id', userId)
            .single();

        if (error || !data) {
            return NextResponse.json(
                { error: 'Job not found' },
                { status: 404 }
            );
        }

        // Type the job properly
        const job: Database['public']['Tables']['jobs']['Row'] = data;

        // When job is completed, fetch the actual clips from the clips table
        let resultData = job.result_data || null;

        if (job.status === 'completed' && !resultData) {
            // Retrieve project_id stored exactly for this job
            const projectId = (job.settings as Record<string, unknown>)?.project_id as string | undefined;

            if (projectId) {
                const { data: projectRaw } = await (supabase
                    .from('projects')
                    .select('id, title')
                    .eq('id', projectId)
                    .single() as unknown as { data: unknown, error: unknown });

                const project = projectRaw as Record<string, unknown> | null;

                if (project) {
                    const { data: clips } = await (supabase
                        .from('clips')
                        .select('*')
                        .eq('project_id', project.id as string) as unknown as { data: unknown[], error: unknown });

                    if (clips && clips.length > 0) {
                        // Helper to extract video ID for thumbnail
                        const extractVideoId = (url: string) => {
                            if (url.includes('v=')) return url.split('v=')[1]?.split('&')[0];
                            if (url.includes('youtu.be/')) return url.split('youtu.be/')[1]?.split('?')[0];
                            return '';
                        };
                        const sourceVideoId = extractVideoId(project.video_url as string || '');
                        const fallbackThumbnail = "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80";

                        resultData = {
                            // eslint-disable-next-line @typescript-eslint/no-explicit-any
                            clips: clips.map((c: any) => ({
                                id: c.id,
                                title: c.title,
                                score: c.virality_score || 0,
                                duration: `${Math.floor((c.end_time || 0) - (c.start_time || 0))}s`,
                                url: c.video_url || '',
                                videoId: sourceVideoId,
                                thumbnailUrl: sourceVideoId ? `https://img.youtube.com/vi/${sourceVideoId}/maxresdefault.jpg` : fallbackThumbnail,
                                startTime: c.start_time,
                                endTime: c.end_time,
                                segments: [{ start: c.start_time, end: c.end_time }],
                                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                                transcript: Array.isArray(c.transcript_segment) ? c.transcript_segment.map((t: any) => ({
                                    timestamp: `${Math.floor((t.time || 0) / 60).toString().padStart(2, '0')}:${Math.floor((t.time || 0) % 60).toString().padStart(2, '0')}`,
                                    text: t.text || ""
                                })) : []
                            })),
                            metadata: {
                                title: project.title as string,
                                duration: 0,
                                hooks_found: clips.length,
                            },
                        };
                    } else if (clips && clips.length === 0) {
                        // Job completed, but 0 clips were successfully generated by the AI
                        resultData = {
                            clips: [],
                            metadata: {
                                title: project.title as string,
                                duration: 0,
                                hooks_found: 0,
                            },
                        };
                    }
                }
            }
        }

        // Return job status with result_data
        return NextResponse.json({
            id: job.id,
            status: job.status,
            created_at: job.created_at,
            result_data: resultData,
            result_url: (job.result_data as { result_url?: string })?.result_url || null, // Legacy field
            error: job.error || null,
            settings: job.settings || null,
        });

    } catch (error) {
        console.error('[API] Job status error:', error);
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        );
    }
}
